site_name: MediaEase
site_url: https://mediaease.github.io/
site_description: Official documentation for the MediaEase Project
site_author: tomcdj71

repo_url: https://github.com/MediaEase/MediaEase
repo_name: MediaEase/docs
edit_uri: blob/main/docs/

# Copyright
copyright: Copyright &copy; 2024 MediaEase

nav:
  - Getting Started:
      - Overview: mediaease/getting_started/index.md
      - Installation: mediaease/getting_started/installation.md
      - Additional Options: mediaease/getting_started/additional-options.md
      - Configure a Domain: mediaease/getting_started/domain.md
      - Configure a RAID Array: mediaease/getting_started/raid-setup.md
      - Full Example: mediaease/getting_started/full-example.md
  - User Guide: mediaease/USER_GUIDE.md
  - Developer Guide: mediaease/DEVELOPER_GUIDE.md
  - Components:
      - HarmonyUI: mediaease/components/harmonyui/README.md
      - Zen: mediaease/components/zen/README.md
      - Mflibs: mediaease/components/mflibs/README.md
      - Binaries: mediaease/components/binaries/README.md
  - API Reference: mediaease/components/api/index.html
  - Zen Scripts:
      - Overview: indexes/scripts-index.md
      - Software:
          - Overview: scripts/software/README.md
          - Official: scripts/software/official.md
          - Community: scripts/software/community.md
      - Command Reference:
          - Overview: indexes/command-index.md
          - API: scripts/command/api/README.md
          - Set: scripts/command/set/README.md
          - Software: scripts/command/software/README.md
          - Support: scripts/command/support/README.md
          - User: scripts/command/user/README.md
  - About:
      - MediaEase: about/mediaease.md
      - HarmonyUI: about/harmonyui.md
      - Zen: about/zen.md
  - Contributing:
      - Code of Conduct: resources/CODE_OF_CONDUCT.md
      - Contributing: resources/CONTRIBUTING.md
      - License: resources/LICENSE.md
      - Security: resources/SECURITY.md

theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/mediaease.png

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - callouts
  - toc:
      permalink: true
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.inlinehilite
